version: "2.4"

networks:
  docker-br0:
    external: true

services:

  #------------------------------------------------------------------------------------------
  ## Master服务
  remoting-master-server:

    # 镜像
    image: docker.apiacmed.com/library/remoting-master:2.3.2-BUILD.SNAPSHOT

    # 系统环境变量设置
    environment:
      - IM_ROLE=MASTER

    # 容器名称
    container_name: remoting-master-cluster-node-2

    ports:
      - 13120:13110         # 注意此处将 13110 映射为13120 是方便同一台前置Nginx进行流量转发
      - 13111:13111

    # 路径映射
    volumes:
      - /tmp/logs/remoting-master:/remoting-master/logs:rw

    # 域名HOST配置
    extra_hosts:
      - node1.mongodb.acmedcare.com:172.172.0.103
      - node2.mongodb.acmedcare.com:172.172.0.104
      - node3.mongodb.acmedcare.com:172.172.0.105

    networks:
      docker-br0:
        ipv4_address: 172.172.0.155

  #------------------------------------------------------------------------------------------
  ## Cluster服务
  remoting-cluster-server:

    image: docker.apiacmed.com/library/remoting-server-wss:2.3.2-BUILD.SNAPSHOT

    container_name: remoting-cluster-wss-node-2

    volumes:
      - /tmp/logs/remoting-cluster:/remoting-server-wss/logs:rw

    # 域名HOST配置
    extra_hosts:
      # 基础服务网关地址
      - gateway.acmedcare.com:172.172.1.108
      # MongoDB副本集集群地址列表
      - node1.mongodb.acmedcare.com:172.172.0.103
      - node2.mongodb.acmedcare.com:172.172.0.104
      - node3.mongodb.acmedcare.com:172.172.0.105

    ports:
      - 43111:43111
      - 23121:23121       # 此处是方便 前置机Nginx流量转发
      - 33111:33111
      - 8889:8888         # 此处是方便 前置机Nginx流量转发

    environment:
      # 对外输出地址HOST
      - EXPORT_HOST=192.168.1.166                                     # 客户端TCP通讯IP,通过Nginx流量转发
      # 对外通讯地址
      - IM_PORT=23121                                                 # 客户端TCP通讯端口
      # 内部Master服务器地址列表
      - NEWIM_MASTER_ADDR=172.172.0.155:13111,172.172.1.155:13111     # Master 主服务器地址
      # 内部主机通讯地址
      - WSS_HOST=192.168.1.152                                        # 宿主机151地址
      # 对外输出WS通讯地址
      - WSS_PORT=8888                                                 # WebSocket地址

    depends_on:
      - remoting-master-server

    networks:
      docker-br0:
        ipv4_address: 172.172.0.160


